2025-07-15 10:10:44.306 #INFO# | [Test info tracking] # test 1 : Réussi
NoneType: None
2025-07-15 10:10:44.312 #INFO# | [Test info tracking] # test 2 : Réussi
NoneType: None
2025-07-15 10:10:44.317 #ERROR# | [Test exception tracking] Raised exception
Traceback (most recent call last):
  File "/home/dreamgeeker/cwest/e-services/projets-python/dreamtools/dreamtest/test_tracking.py", line 13, in test_tracking_exception
    raise Exception ('Raised exception')
Exception: Raised exception
2025-07-15 10:13:47.819 #INFO# | [Test info tracking] # test 1 : Réussi
NoneType: None
2025-07-15 10:13:47.824 #INFO# | [Test info tracking] # test 2 : Réussi
NoneType: None
2025-07-15 10:13:47.830 #ERROR# | [Test exception tracking] Raised exception
Traceback (most recent call last):
  File "/home/dreamgeeker/cwest/e-services/projets-python/dreamtools/dreamtest/test_tracking.py", line 13, in test_tracking_exception
    raise Exception ('Raised exception')
Exception: Raised exception
2025-07-15 10:15:30.135 #INFO# | [Test info tracking] # test 1 : Réussi
NoneType: None
2025-07-15 10:15:30.140 #INFO# | [Test info tracking] # test 2 : Réussi
NoneType: None
2025-07-15 10:15:30.146 #ERROR# | [Test exception tracking] Raised exception
Traceback (most recent call last):
  File "/home/dreamgeeker/cwest/e-services/projets-python/dreamtools/dreamtest/test_tracking.py", line 13, in test_tracking_exception
    raise Exception ('Raised exception')
Exception: Raised exception
2025-07-15 10:15:55.068 #INFO# | [Test info tracking] # test 1 : Réussi
NoneType: None
2025-07-15 10:15:55.073 #INFO# | [Test info tracking] # test 2 : Réussi
NoneType: None
2025-07-15 10:15:55.078 #ERROR# | [Test exception tracking] Raised exception
Traceback (most recent call last):
  File "/home/dreamgeeker/cwest/e-services/projets-python/dreamtools/dreamtest/test_tracking.py", line 13, in test_tracking_exception
    raise Exception ('Raised exception')
Exception: Raised exception
